Fix the error when launch pytest by updating conftest.py. Update config.py and .gitignore
Solved error message:
password = quote_plus(os.environ.get("POSTGRES_PASSWORD"))
TypeError: quote_from_bytes() expected bytes

The reason of error occurred:
In the process of pytest, environment variables were not loaded from .env because load_dotenv() is not called in conftest.py

conftest.py
- add load_dotenv() at the beginning of code

config.py
- move password escaping of postgresql to DevelopmentConfig and ProductionConfig

.gitignore
- add .vscode/